matrix:
  include:
    - os: linux
      dist: precise
      compiler: gcc
    - os: linux
      dist: precise
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
    - os: windows
sudo: false
language: cpp
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install re2c ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install re2c python ; fi
script:
  - ./misc/ci.py
  - python3 configure.py --bootstrap
  - ./ninja all
  - ./ninja_test --gtest_filter=-SubprocessTest.SetWithLots
  - ./misc/ninja_syntax_test.py
  - ./misc/output_test.py
