version: 1.0.{build}
image:
  - Ubuntu1604
  - Ubuntu1804
  - Visual Studio 2017

environment:
  CLICOLOR_FORCE: 1
  CHERE_INVOKING: 1 # Tell Bash to inherit the current working directory
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MSVC
    - MSYSTEM: LINUX

matrix:
  exclude:
    - image: Ubuntu1604
      MSYSTEM: MINGW64
    - image: Ubuntu1604
      MSYSTEM: MSVC
    - image: Ubuntu1804
      MSYSTEM: MINGW64
    - image: Ubuntu1804
      MSYSTEM: MSVC
    - image: Visual Studio 2017
      MSYSTEM: LINUX

for:
  - matrix:
      only:
        - image: Ubuntu1604
    install:
      - sudo apt install -y re2c
      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10 --slave /usr/bin/g++ g++ /usr/bin/g++-7
      - sudo update-alternatives --set gcc /usr/bin/gcc-7
    build_script:
      - ./misc/ci.py
      - ./configure.py --bootstrap
      - ./ninja all
      - ./ninja_test
      - misc/ninja_syntax_test.py
      - misc/output_test.py

  - matrix:
      only:
        - image: Ubuntu1804
    install: sudo apt install -y re2c
    build_script:
      - ./misc/ci.py
      - ./configure.py --bootstrap
      - ./ninja all
      - ./ninja_test
      - misc/ninja_syntax_test.py
      - misc/output_test.py

  - matrix:
      only:
        - MSYSTEM: MINGW64
    install:
      ps: "C:\\msys64\\usr\\bin\\bash -lc \"pacman -S --quiet --noconfirm --needed re2c 2>&1\""
    build_script:
      ps: "C:\\msys64\\usr\\bin\\bash -lc @\"\n
      ./misc/ci.py 2>&1\n
      ./configure.py --bootstrap --platform mingw 2>&1\n
      ./ninja all\n
      ./ninja_test 2>&1\n
      ./misc/ninja_syntax_test.py 2>&1\n\"@"

  - matrix:
      only:
        - MSYSTEM: MSVC
    install: cinst re2c
    build_script:
    - cmd: >-
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

        python misc/ci.py

        python configure.py --bootstrap

        ninja.bootstrap.exe all

        ninja_test

        python misc/ninja_syntax_test.py

test: off
